version: '3.9'
services:
  mongo:
    image: mongo:7
    container_name: e-shop-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: e-shop-backend
    command: npm run start:dev
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: e-shop-frontend
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_URL: http://localhost:4000
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
