version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: coffee-postgres
    restart: unless-stopped 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: coffee-nest
    command: npm run start:dev
    ports:
    - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: coffee-nuxt
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_URL: http://localhost:4000
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db-data: